### ISSUE TITLE
Error: Unclosed [ at character

### ISSUE THREAD

**Issue by tylerlong** [tylerlong/vscode-openapi-linter#11]
```
c:\Users\username\.vscode\extensions\chuntaoliu.openapi-linter-0.4.0\server\node_modules\jsep\dist\cjs\jsep.cjs.js:337
        const error = new Error(message + ' at character ' + this.index);
                      ^

Error: Unclosed [ at character 54
    at Jsep.throwError (c:\Users\username\.vscode\extensions\chuntaoliu.openapi-linter-0.4.0\server\node_modules\jsep\dist\cjs\jsep.cjs.js:337:17)
    at Jsep.gobbleTokenProperty (c:\Users\username\.vscode\extensions\chuntaoliu.openapi-linter-0.4.0\server\node_modules\jsep\dist\cjs\jsep.cjs.js:687:11)
    at Jsep.gobbleToken (c:\Users\username\.vscode\extensions\chuntaoliu.openapi-linter-0.4.0\server\node_modules\jsep\dist\cjs\jsep.cjs.js:648:15)
    at Jsep.gobbleBinaryExpression (c:\Users\username\.vscode\extensions\chuntaoliu.openapi-linter-0.4.0\server\node_modules\jsep\dist\cjs\jsep.cjs.js:545:16)
    at Jsep.gobbleExpression (c:\Users\username\.vscode\extensions\chuntaoliu.openapi-linter-0.4.0\server\node_modules\jsep\dist\cjs\jsep.cjs.js:447:61)
    at Jsep.gobbleExpressions (c:\Users\username\.vscode\extensions\chuntaoliu.openapi-linter-0.4.0\server\node_modules\jsep\dist\cjs\jsep.cjs.js:425:21)
    at Jsep.parse (c:\Users\username\.vscode\extensions\chuntaoliu.openapi-linter-0.4.0\server\node_modules\jsep\dist\cjs\jsep.cjs.js:395:22)
    at Function.parse (c:\Users\username\.vscode\extensions\chuntaoliu.openapi-linter-0.4.0\server\node_modules\jsep\dist\cjs\jsep.cjs.js:281:27)
    at Object.jsep [as default] (c:\Users\username\.vscode\extensions\chuntaoliu.openapi-linter-0.4.0\server\node_modules\nimma\dist\legacy\cjs\parser\jsep.js:20:46)
    at onlyFilterScriptExpression (c:\Users\username\.vscode\extensions\chuntaoliu.openapi-linter-0.4.0\server\node_modules\nimma\dist\legacy\cjs\codegen\fast-paths\only-filter-script-expression.js:19:97) {
  index: 54,
  description: 'Unclosed ['
}
[Error - 5:15:31 PM] The OpenAPI Linter server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

Problem disappeared after restarting vscode.

**Comment by tylerlong** [comment]
It happens with you select a file, but haven't opened it by double click.
